server:
  port: 8070
  
msg: anglabace

debug: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  
security: 
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: svcb-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server

logging:
  config: classpath:logback.xml
  path: d:/logs
  level:
    org.springframework.web: INFO
    com.ewx.cp: DEBUG
    me.chanjar.weixin: DEBUG
    
# 上传文件总的最大值
spring:
   servlet:
      multipart:
         max-request-size:10MB
         max-file-size:10MB
# 单个文件的最大值


    
wechat:
  cp:
    corpId: ww68b69d00c9a75c5a
    appConfigs:
      - agentId: 1000002
        secret: mcX35sedGRq1fP_gv9-l35K7b7_1RNbZ8dlgJByrvMQ
        token: fv0JMUcF0Bdl86kwQAxvsbBhPeTy
        aesKey: Yasm4wULy6QeHqYiwRIm3kORmVWm0cRmcLqrvDh3xbt
  
mybatis:
     mapperLocations: classpath:/com/ewx/cp/dao/*.xml
     typeAliasesPackage: com.ewx.cp.dao    
     mapperScanPackage: com.ewx.cp.dao
     configLocation: classpath:/mybatis-config.xml

mysql:
    datasource:
        readSize: 2  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath:/com/ewx/cp/dao/*.xml
        configLocation: classpath:/mybatis-config.xml
        write:
           url: jdbc:mysql://10.18.178.217:50501/test?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
           username: anglabace
           password: zxc123150@
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read01:
           url: jdbc:mysql://10.18.178.217:50501/test_01?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
           username: anglabace
           password: zxc123150@
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read02:
           url: jdbc:mysql://10.18.178.217:50501/test_02?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
           username: anglabace
           password: zxc123150@
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat       
