application:
  #版本
  version: 1.0.0
  #文件上传路径
  profile: D:/profile/
  profileurl: http://localhost/app/files/
  profilemap: /files/**

weixin:
  sendmsg:
    retrycount: 5
  
server:
  port: 80
  tomcat:
    basedir: D:/profile/temp/  

web:
  upload-path: E:/
  

msg: anglabace

word:
  to:
    html:
      path: /tmp/doc/

    
debug: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

management:
  security:
    enabled: false
  
security: 
  basic:
    enabled: false
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: svcd-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server

logging:
  config: classpath:logback.xml
  path: d:/logs
  level:
    org.springframework.web: INFO
    com.jsnx.ewx.ueditor: DEBUG
    me.chanjar.weixin: DEBUG 
    
# 上传文件总的最大值
spring:
   mvc:
      static-path-pattern: /**  
   resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
   http:
      multipart:
         max-request-size: 10MB
         max-file-size: 10MB
         enabled: true
# 单个文件的最大值
