application:
  #版本
  version: 1.0.0
  #文件上传路径
  profile: D:/profile/
  profileurl: http://localhost/app/files/
  profilemap: /files/**

awss3:
  #版本
  version: 1.0.0
  bucketName: awstest
  accessKey: C488JQZT9GG9HGG48Y3C
  secretKey: dFTi9b+DXlPP0GoKHDDz4e40quUaeMjqgo8DK8+Y
  endpoint: http://10.18.176.248:9000
  publicurl: http://10.18.176.248:9000
  newurlstatus: 0
  
weixin:
  sendmsg:
    retrycount: 5
  
server:
  port: 8270
  tomcat:
    basedir: D:/profile/temp/
  
msg: anglabace

debug: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

management:
  security:
    enabled: false
  
security: 
  basic:
    enabled: false
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: svcc-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server

logging:
  config: classpath:logback.xml
  path: d:/logs
  level:
    org.springframework.web: INFO
    com.ewx.file: DEBUG
    me.chanjar.weixin: DEBUG
    com.ewx.file.dao: DEBUG 
    
# 上传文件总的最大值
spring:
   http:
      multipart:
         max-request-size: 200MB
         max-file-size: 200MB
# 单个文件的最大值


  
mybatis:
     mapperLocations: classpath:/com/ewx/file/dao/*.xml
     typeAliasesPackage: com.ewx.file.pojo    
     mapperScanPackage: com.ewx.file.dao
     configLocation: classpath:/mybatis-config.xml
#     type-aliases-package: com.ewx.cp.pojo


mysql:
    datasource:
        readSize: 2  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath:/com/ewx/file/dao/*.xml
        configLocation: classpath:/mybatis-config.xml
        write:
           url: jdbc:mysql://10.18.178.217:4706/jsnx_workflow?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
           username: anglabace
           password: Wewechat
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
           connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
           useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
           druidLoginName: wjf # 登录druid的账号
           druidPassword: wjf # 登录druid的密码
        read01:
           url: jdbc:mysql://10.18.178.217:4706/jsnx_workflow?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
           username: anglabace
           password: Wewechat
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
           connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
           useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
           druidLoginName: wjf # 登录druid的账号
           druidPassword: wjf # 登录druid的密码
        read02:
           url: jdbc:mysql://10.18.178.217:4706/jsnx_workflow?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
           username: anglabace
           password: Wewechat
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
           connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
           useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
           druidLoginName: wjf # 登录druid的账号
           druidPassword: wjf # 登录druid的密码       
