server:
  port: 8960

management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  # 饥饿加载
  eager-load:
    # 是否开启饥饿加载
    enabled: true
    # 饥饿加载的服务
    clients: svcb-service,zuul-reverse-proxy,ewx-personal-management-service  
    
spring:
  rabbitmq:
    host: 127.0.0.1
    username: anglabace
    password: zxc123150
    virtualHost: /    

zuul:
  routes:
    fanruan-api:
      path: /finereport/**
      url: http://10.18.176.248:8010
